name: docs

# 每当某个行为发生的时候讲触发动作
on:
  # 当 push 到 main 分支时触发工作流
  push:
    branches: [main]
  # 当 xxx 规则时触发工作流（当前为空）
  workflow_dispatch:

# 工作流中需要做的任务清单（每个 job 可以自己命名，并且相互之间默认是并行执行的独立关系，除非使用 needs）
jobs:
  # 文档任务（当前只有一个任务）
  docs:
    # 指定环境
    runs-on: ubuntu-latest

    # 指定步骤
    steps:
      - name: 把触发 workflow 的那个仓库 clone 到 runner 的工作目录，把仓库“搬到” CI/CD 虚拟机上方便后续构建、测试、部署
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置指定的 Node.js 依赖管理器和对应的版本
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 安装依赖
        run: |
          cd work-blog-website-frontend
          npm install

      - name: 构建项目
        run: |
          cd work-blog-website-frontend
          npm run docs:build

      - name: 部署服务
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages # 部署到 gh-pages 分支
          build_dir: work-blog-website-frontend/docs/.vuepress/dist # 部署目录为 VuePress 的默认输出目录
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
